import type { User, Event, Registration, Venue, VenueRequest, PaymentVerification, OrganizerApplication } from './types'

export const mockUsers: User[] = [
  {
    id: 'student-1',
    name: 'Nimal Perera',
    email: 'nimal@uom.lk',
    role: 'student',
    department: 'Computer Science & Engineering',
    indexNumber: '210456P',
    status: 'active',
  },
  {
    id: 'student-2',
    name: 'Sanduni Fernando',
    email: 'sanduni@uom.lk',
    role: 'student',
    department: 'Electronic & Telecommunication',
    indexNumber: '210234T',
    status: 'active',
  },
  {
    id: 'organizer-1',
    name: 'Kamal Silva',
    email: 'kamal@uom.lk',
    role: 'organizer',
    department: 'Computer Science & Engineering',
    status: 'active',
  },
  {
    id: 'organizer-2',
    name: 'Malini Jayasinghe',
    email: 'malini@uom.lk',
    role: 'organizer',
    department: 'Electrical Engineering',
    status: 'active',
  },
  {
    id: 'venue-manager-1',
    name: 'Sunil Rathnayake',
    email: 'sunil@uom.lk',
    role: 'venue_manager',
    department: 'Administration',
    status: 'active',
  },
  {
    id: 'treasurer-1',
    name: 'Priyani Kumari',
    email: 'priyani@uom.lk',
    role: 'treasurer',
    department: 'Finance',
    status: 'active',
  },
  {
    id: 'dean-1',
    name: 'Mahesh Bandara',
    email: 'mahesh@uom.lk',
    role: 'dean',
    department: 'Faculty of Engineering',
    status: 'active',
  },
  {
    id: 'vc-1',
    name: 'Anura Wijesinghe',
    email: 'anura@uom.lk',
    role: 'vice_chancellor',
    department: 'Vice Chancellor Office',
    status: 'active',
  },
  {
    id: 'admin-1',
    name: 'Ruwan Gunawardhane',
    email: 'ruwan@uom.lk',
    role: 'admin',
    department: 'IT Administration',
    status: 'active',
  },
]

export const mockActivityLog = [
  { id: '1', action: 'User Login', user: 'Nimal Perera', timestamp: '2 minutes ago', type: 'info' },
  { id: '2', action: 'Event Created', user: 'Kamal Silva', timestamp: '1 hour ago', type: 'success' },
  { id: '3', action: 'Venue Blocked', user: 'Sunil Rathnayake', timestamp: '3 hours ago', type: 'warning' },
  { id: '4', action: 'Payment Verified', user: 'Priyani Kumari', timestamp: '5 hours ago', type: 'success' },
  { id: '5', action: 'User Registered', user: 'Sanduni Fernando', timestamp: 'Yesterday', type: 'info' },
  { id: '6', action: 'Event Rejected', user: 'Mahesh Bandara', timestamp: 'Yesterday', type: 'error' },
  { id: '7', action: 'System Backup', user: 'System', timestamp: '2 days ago', type: 'info' },
  { id: '8', action: 'New Organizer App', user: 'Chathura Priyadarshana', timestamp: '3 days ago', type: 'info' },
  { id: '9', action: 'Settings Updated', user: 'Ruwan Gunawardhane', timestamp: '4 days ago', type: 'warning' },
  { id: '10', action: 'Report Generated', user: 'Ruwan Gunawardhane', timestamp: '1 week ago', type: 'success' },
]

export const mockReports = [
  { id: '1', name: 'Monthly User Growth', type: 'User Report', date: '2026-03-01', format: 'PDF', status: 'ready' },
  { id: '2', name: 'Q1 Financial Summary', type: 'Financial Report', date: '2026-03-15', format: 'Excel', status: 'ready' },
  { id: '3', name: 'Event Attendance', type: 'Attendance Report', date: '2026-03-10', format: 'CSV', status: 'ready' },
  { id: '4', name: 'System Usage', type: 'System Report', date: '2026-03-20', format: 'PDF', status: 'processing' },
]

export const mockEvents: Event[] = [
  {
    id: 'event-1',
    name: 'AI & Machine Learning Workshop',
    description: 'A comprehensive workshop on artificial intelligence and machine learning fundamentals. Learn about neural networks, deep learning, and practical applications.',
    category: 'academic',
    date: '2026-02-15',
    time: '09:00 - 16:00',
    venue: 'Senate Hall',
    venueId: 'venue-1',
    capacity: 200,
    registeredCount: 145,
    price: 0,
    isFree: true,
    organizer: 'Kamal Silva',
    organizerId: 'organizer-1',
    department: 'Computer Science & Engineering',
    status: 'approved',
    approvalChain: [
      { level: 'venue_manager', status: 'approved', approverName: 'Sunil Rathnayake', date: '2026-01-10' },
      { level: 'treasurer', status: 'approved', approverName: 'Priyani Kumari', date: '2026-01-11' },
      { level: 'dean', status: 'approved', approverName: 'Mahesh Bandara', date: '2026-01-12' },
      { level: 'vice_chancellor', status: 'approved', approverName: 'Anura Wijesinghe', date: '2026-01-13' },
    ],
    createdAt: '2026-01-05',
  },
  {
    id: 'event-2',
    name: 'Mora Night 2026',
    description: 'The most awaited annual musical concert featuring top Sri Lankan artists. An unforgettable night of entertainment and celebration.',
    category: 'entertainment',
    date: '2026-03-20',
    time: '18:00 - 23:00',
    venue: 'University Grounds',
    venueId: 'venue-3',
    capacity: 5000,
    registeredCount: 3200,
    price: 1500,
    isFree: false,
    organizer: 'Malini Jayasinghe',
    organizerId: 'organizer-2',
    department: 'Student Union',
    status: 'approved',
    approvalChain: [
      { level: 'venue_manager', status: 'approved', approverName: 'Sunil Rathnayake', date: '2026-01-20' },
      { level: 'treasurer', status: 'approved', approverName: 'Priyani Kumari', date: '2026-01-21' },
      { level: 'dean', status: 'approved', approverName: 'Mahesh Bandara', date: '2026-01-22' },
      { level: 'vice_chancellor', status: 'approved', approverName: 'Anura Wijesinghe', date: '2026-01-23' },
    ],
    createdAt: '2026-01-15',
  },
  {
    id: 'event-3',
    name: 'Inter-Faculty Cricket Tournament',
    description: 'Annual cricket tournament between all faculties. Show your support for your faculty team!',
    category: 'sports',
    date: '2026-02-28',
    time: '08:00 - 18:00',
    venue: 'University Cricket Ground',
    venueId: 'venue-4',
    capacity: 1000,
    registeredCount: 450,
    price: 0,
    isFree: true,
    organizer: 'Kamal Silva',
    organizerId: 'organizer-1',
    department: 'Sports Council',
    status: 'approved',
    approvalChain: [
      { level: 'venue_manager', status: 'approved', approverName: 'Sunil Rathnayake', date: '2026-01-25' },
      { level: 'treasurer', status: 'approved', approverName: 'Priyani Kumari', date: '2026-01-26' },
      { level: 'dean', status: 'approved', approverName: 'Mahesh Bandara', date: '2026-01-27' },
      { level: 'vice_chancellor', status: 'approved', approverName: 'Anura Wijesinghe', date: '2026-01-28' },
    ],
    createdAt: '2026-01-20',
  },
  {
    id: 'event-4',
    name: 'Traditional Dance Festival',
    description: 'Celebrating Sri Lankan heritage through traditional dance performances from all regions.',
    category: 'cultural',
    date: '2026-04-10',
    time: '14:00 - 20:00',
    venue: 'Open Air Theatre',
    venueId: 'venue-2',
    capacity: 800,
    registeredCount: 320,
    price: 500,
    isFree: false,
    organizer: 'Malini Jayasinghe',
    organizerId: 'organizer-2',
    department: 'Cultural Society',
    status: 'pending_approval',
    approvalChain: [
      { level: 'venue_manager', status: 'approved', approverName: 'Sunil Rathnayake', date: '2026-01-28' },
      { level: 'treasurer', status: 'pending' },
      { level: 'dean', status: 'pending' },
      { level: 'vice_chancellor', status: 'pending' },
    ],
    createdAt: '2026-01-25',
  },
  {
    id: 'event-5',
    name: 'Robotics Competition',
    description: 'Annual robotics competition showcasing innovative robot designs and autonomous systems.',
    category: 'technical',
    date: '2026-03-05',
    time: '09:00 - 17:00',
    venue: 'Engineering Auditorium',
    venueId: 'venue-5',
    capacity: 500,
    registeredCount: 280,
    price: 200,
    isFree: false,
    organizer: 'Kamal Silva',
    organizerId: 'organizer-1',
    department: 'Mechatronics Society',
    status: 'pending_venue',
    approvalChain: [
      { level: 'venue_manager', status: 'pending' },
      { level: 'treasurer', status: 'pending' },
      { level: 'dean', status: 'pending' },
      { level: 'vice_chancellor', status: 'pending' },
    ],
    createdAt: '2026-01-28',
  },
  {
    id: 'event-6',
    name: 'Career Fair 2026',
    description: 'Connect with top employers and explore career opportunities. Over 50 companies participating.',
    category: 'academic',
    date: '2026-02-20',
    time: '09:00 - 17:00',
    venue: 'Senate Hall',
    venueId: 'venue-1',
    capacity: 1000,
    registeredCount: 1000,
    price: 0,
    isFree: true,
    organizer: 'Malini Jayasinghe',
    organizerId: 'organizer-2',
    department: 'Career Guidance Unit',
    status: 'approved',
    approvalChain: [
      { level: 'venue_manager', status: 'approved', approverName: 'Sunil Rathnayake', date: '2026-01-05' },
      { level: 'treasurer', status: 'approved', approverName: 'Priyani Kumari', date: '2026-01-06' },
      { level: 'dean', status: 'approved', approverName: 'Mahesh Bandara', date: '2026-01-07' },
      { level: 'vice_chancellor', status: 'approved', approverName: 'Anura Wijesinghe', date: '2026-01-08' },
    ],
    createdAt: '2026-01-01',
  },
  {
    id: 'event-7',
    name: 'Tech Talk: Future of AI',
    description: 'Join us for an insightful session on the future of Artificial Intelligence, featuring industry experts from leading tech companies.',
    category: 'technical',
    date: '2026-03-15',
    time: '14:00 - 16:00',
    venue: 'Senate Hall',
    venueId: 'venue-1',
    capacity: 200,
    registeredCount: 50,
    price: 0,
    isFree: true,
    organizer: 'Kamal Silva',
    organizerId: 'organizer-1',
    department: 'Computer Science & Engineering',
    status: 'approved',
    approvalChain: [
      { level: 'venue_manager', status: 'approved', approverName: 'Sunil Rathnayake', date: '2026-02-01' },
      { level: 'treasurer', status: 'approved', approverName: 'Priyani Kumari', date: '2026-02-02' },
      { level: 'dean', status: 'approved', approverName: 'Mahesh Bandara', date: '2026-02-03' },
      { level: 'vice_chancellor', status: 'approved', approverName: 'Anura Wijesinghe', date: '2026-02-04' },
    ],
    createdAt: '2026-01-25',
  },
  {
    id: 'event-8',
    name: 'Photography Workshop',
    description: 'Master the art of photography in this hands-on workshop. Learn composition, lighting, and post-processing techniques.',
    category: 'cultural',
    date: '2026-03-25',
    time: '09:00 - 13:00',
    venue: 'Library Seminar Room',
    venueId: 'venue-6',
    capacity: 50,
    registeredCount: 15,
    price: 1000,
    isFree: false,
    organizer: 'Malini Jayasinghe',
    organizerId: 'organizer-2',
    department: 'Media Unit',
    status: 'approved',
    approvalChain: [
      { level: 'venue_manager', status: 'approved', approverName: 'Sunil Rathnayake', date: '2026-02-10' },
      { level: 'treasurer', status: 'approved', approverName: 'Priyani Kumari', date: '2026-02-11' },
      { level: 'dean', status: 'approved', approverName: 'Mahesh Bandara', date: '2026-02-12' },
      { level: 'vice_chancellor', status: 'approved', approverName: 'Anura Wijesinghe', date: '2026-02-13' },
    ],
    createdAt: '2026-02-05',
  },
]

export const mockRegistrations: Registration[] = [
  {
    id: 'reg-1',
    eventId: 'event-1',
    eventName: 'AI & Machine Learning Workshop',
    studentId: 'student-1',
    studentName: 'Nimal Perera',
    indexNumber: '210456P',
    status: 'registered',
    qrCode: 'QR-AI-210456P-2026',
    registeredAt: '2026-01-14',
  },
  {
    id: 'reg-2',
    eventId: 'event-2',
    eventName: 'Mora Night 2026',
    studentId: 'student-1',
    studentName: 'Nimal Perera',
    indexNumber: '210456P',
    status: 'pending_payment',
    paymentSlipUrl: '/payment-slip-1.jpg',
    transactionRef: 'TXN123456',
    registeredAt: '2026-01-20',
  },
  {
    id: 'reg-3',
    eventId: 'event-3',
    eventName: 'Inter-Faculty Cricket Tournament',
    studentId: 'student-1',
    studentName: 'Nimal Perera',
    indexNumber: '210456P',
    status: 'registered',
    qrCode: 'QR-CRICKET-210456P-2026',
    registeredAt: '2026-01-26',
  },
  {
    id: 'reg-4',
    eventId: 'event-4',
    eventName: 'Traditional Dance Festival',
    studentId: 'student-2',
    studentName: 'Sanduni Fernando',
    indexNumber: '210234T',
    status: 'payment_rejected',
    paymentSlipUrl: '/payment-slip-2.jpg',
    rejectionReason: 'Bank slip image is blurry and amount is not visible',
    registeredAt: '2026-01-27',
  },
]

export const mockVenues: Venue[] = [
  {
    id: 'venue-1',
    name: 'Senate Hall',
    capacity: 500,
    facilities: ['Projector', 'Sound System', 'Air Conditioning', 'WiFi'],
    status: 'available',
    blockedDates: [],
  },
  {
    id: 'venue-2',
    name: 'Open Air Theatre',
    capacity: 1000,
    facilities: ['Stage', 'Sound System', 'Lighting'],
    status: 'available',
    blockedDates: [],
  },
  {
    id: 'venue-3',
    name: 'University Grounds',
    capacity: 10000,
    facilities: ['Open Space', 'Power Supply', 'Parking'],
    status: 'available',
    blockedDates: [],
  },
  {
    id: 'venue-4',
    name: 'University Cricket Ground',
    capacity: 2000,
    facilities: ['Cricket Pitch', 'Seating', 'Scoreboard'],
    status: 'available',
    blockedDates: [],
  },
  {
    id: 'venue-5',
    name: 'Engineering Auditorium',
    capacity: 600,
    facilities: ['Projector', 'Sound System', 'Air Conditioning', 'WiFi', 'Recording Equipment'],
    status: 'available',
    blockedDates: [],
  },
  {
    id: 'venue-6',
    name: 'Library Seminar Room',
    capacity: 100,
    facilities: ['Projector', 'Whiteboard', 'Air Conditioning', 'WiFi'],
    status: 'maintenance',
    blockedDates: [{ start: '2026-01-20', end: '2026-02-10', reason: 'Renovation work' }],
  },
]

export const mockVenueRequests: VenueRequest[] = [
  {
    id: 'vr-1',
    eventId: 'event-5',
    eventName: 'Robotics Competition',
    organizerName: 'Kamal Silva',
    organizerDepartment: 'Mechatronics Society',
    venueId: 'venue-5',
    venueName: 'Engineering Auditorium',
    requestedDate: '2026-03-05',
    requestedTime: '09:00 - 17:00',
    status: 'pending',
    createdAt: '2026-01-28',
  },
  {
    id: 'vr-2',
    eventId: 'event-7',
    eventName: 'Guest Lecture: Sustainable Engineering',
    organizerName: 'Malini Jayasinghe',
    organizerDepartment: 'Civil Engineering',
    venueId: 'venue-1',
    venueName: 'Senate Hall',
    requestedDate: '2026-02-25',
    requestedTime: '14:00 - 16:00',
    status: 'pending',
    createdAt: '2026-01-29',
  },
]

export const mockPaymentVerifications: PaymentVerification[] = [
  {
    id: 'pv-1',
    registrationId: 'reg-2',
    studentName: 'Nimal Perera',
    studentIndex: '210456P',
    eventName: 'Mora Night 2026',
    eventId: 'event-2',
    amount: 1500,
    slipUrl: '/payment-slip-1.jpg',
    transactionRef: 'TXN123456',
    uploadedAt: '2026-01-20',
    status: 'pending',
  },
  {
    id: 'pv-2',
    registrationId: 'reg-5',
    studentName: 'Amal Gunasekara',
    studentIndex: '210567E',
    eventName: 'Mora Night 2026',
    eventId: 'event-2',
    amount: 1500,
    slipUrl: '/payment-slip-3.jpg',
    transactionRef: 'TXN789012',
    uploadedAt: '2026-01-21',
    status: 'pending',
  },
  {
    id: 'pv-3',
    registrationId: 'reg-6',
    studentName: 'Dinesh Priyantha',
    studentIndex: '210890M',
    eventName: 'Traditional Dance Festival',
    eventId: 'event-4',
    amount: 500,
    slipUrl: '/payment-slip-4.jpg',
    uploadedAt: '2026-01-28',
    status: 'pending',
  },
]

export const mockOrganizerApplications: OrganizerApplication[] = [
  {
    id: 'oa-1',
    userId: 'user-10',
    name: 'Chathura Priyadarshana',
    email: 'chatura@uom.lk',
    department: 'Mechanical Engineering',
    reason: 'I want to organize technical workshops and seminars for my department students.',
    status: 'pending',
    appliedAt: '2026-01-25',
  },
  {
    id: 'oa-2',
    userId: 'user-11',
    name: 'Hiruni Madushani',
    email: 'hiruni@uom.lk',
    department: 'Architecture',
    reason: 'Planning to organize design exhibitions and guest lectures from industry professionals.',
    status: 'pending',
    appliedAt: '2026-01-27',
  },
]

export const loginCredentials = {
  student: { email: 'nimal@uom.lk', password: 'student123' },
  organizer: { email: 'kamal@uom.lk', password: 'organizer123' },
  venue_manager: { email: 'sunil@uom.lk', password: 'venue123' },
  treasurer: { email: 'priyani@uom.lk', password: 'treasurer123' },
  dean: { email: 'mahesh@uom.lk', password: 'dean123' },
  vice_chancellor: { email: 'anura@uom.lk', password: 'vc123' },
  admin: { email: 'ruwan@uom.lk', password: 'admin123' },
}
